version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven dependencies...
      - mvn install

  build:
    commands:
      - echo Building project...
      - mvn package

artifacts:
  files:
    - target/ReminderLambda-0.0.1-SNAPSHOT.jar
