version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build started
      - mvn package -DskipTests
artifacts:
  files:
    - target/*.jar
